name: Build

on:
  workflow_call:
    secrets:
      CI_TOKEN:
        required: true

permissions:
  pull-requests: write
  statuses: write
  contents: write
  checks: write

jobs:
  assembleDebug:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Create local.properties
        run: echo > local.properties

      - name: Build app
        run: ./gradlew :app:assembleDebug
